import { SalesRecord } from '../types';

export const SAMPLE_SHEET_HEADERS = [
  'Date',
  'Order_ID',
  'SKU',
  'Product_Name',
  'Category',
  'Units_Sold',
  'Unit_Price',
  'Revenue',
  'Unit_Cost',
  'Gross_Profit',
  'Current_Stock',
  'Safety_Stock_Threshold',
  'Lead_Time_Days',
  'Supplier'
];

export const INITIAL_SAMPLE_SALES: SalesRecord[] = [
  {
    id: 'pub-01',
    date: '2026-09-01',
    orderId: 'PUB-1041',
    sku: 'BEER-TSK-500',
    productName: 'Tusker Lager 500ml Bottle',
    category: 'Beers & Ciders',
    unitsSold: 48,
    unitPrice: 300,
    revenue: 14400,
    unitCost: 210,
    profit: 4320,
    profitMarginPercent: 30.0,
    currentStock: 36,
    reorderPoint: 72,
    leadTimeDays: 2,
    supplier: 'EABL Central Depot (Ruaraka)'
  },
  {
    id: 'pub-02',
    date: '2026-09-01',
    orderId: 'PUB-1042',
    sku: 'FOOD-MBZ-1KG',
    productName: 'Mbuzi Choma (1kg Roasted Goat Meat)',
    category: 'Choma & Pub Kitchen',
    unitsSold: 8,
    unitPrice: 1400,
    revenue: 11200,
    unitCost: 850,
    profit: 4400,
    profitMarginPercent: 39.3,
    currentStock: 8,
    reorderPoint: 25,
    leadTimeDays: 1,
    supplier: 'Dagoretti Livestock & Meat Supply'
  },
  {
    id: 'pub-03',
    date: '2026-09-02',
    orderId: 'PUB-1043',
    sku: 'BEER-WTC-500',
    productName: 'White Cap Lager 500ml Bottle',
    category: 'Beers & Ciders',
    unitsSold: 28,
    unitPrice: 300,
    revenue: 8400,
    unitCost: 215,
    profit: 2380,
    profitMarginPercent: 28.3,
    currentStock: 24,
    reorderPoint: 48,
    leadTimeDays: 2,
    supplier: 'EABL Central Depot (Ruaraka)'
  },
  {
    id: 'pub-04',
    date: '2026-09-02',
    orderId: 'PUB-1044',
    sku: 'SPRT-KC-750',
    productName: 'Kenya Cane Original (KC) 750ml',
    category: 'Spirits & Liquors',
    unitsSold: 6,
    unitPrice: 1100,
    revenue: 6600,
    unitCost: 750,
    profit: 2100,
    profitMarginPercent: 31.8,
    currentStock: 14,
    reorderPoint: 20,
    leadTimeDays: 3,
    supplier: 'UDV Kenya Ltd (Nairobi)'
  },
  {
    id: 'pub-05',
    date: '2026-09-03',
    orderId: 'PUB-1045',
    sku: 'FOOD-MUTURA-PC',
    productName: 'African Spiced Sausage (Mutura)',
    category: 'Choma & Pub Kitchen',
    unitsSold: 35,
    unitPrice: 150,
    revenue: 5250,
    unitCost: 60,
    profit: 3150,
    profitMarginPercent: 60.0,
    currentStock: 18,
    reorderPoint: 40,
    leadTimeDays: 1,
    supplier: 'Dagoretti Livestock & Meat Supply'
  },
  {
    id: 'pub-06',
    date: '2026-09-03',
    orderId: 'PUB-1046',
    sku: 'BEER-GNS-500',
    productName: 'Guinness Foreign Extra Stout 500ml',
    category: 'Beers & Ciders',
    unitsSold: 22,
    unitPrice: 350,
    revenue: 7700,
    unitCost: 245,
    profit: 2310,
    profitMarginPercent: 30.0,
    currentStock: 12,
    reorderPoint: 48,
    leadTimeDays: 2,
    supplier: 'EABL Central Depot (Ruaraka)'
  },
  {
    id: 'pub-07',
    date: '2026-09-04',
    orderId: 'PUB-1047',
    sku: 'SPRT-GLB-750',
    productName: 'Gilbeys Special Dry Gin 750ml',
    category: 'Spirits & Liquors',
    unitsSold: 9,
    unitPrice: 1600,
    revenue: 14400,
    unitCost: 1120,
    profit: 4320,
    profitMarginPercent: 30.0,
    currentStock: 6,
    reorderPoint: 25,
    leadTimeDays: 3,
    supplier: 'UDV Kenya Ltd (Nairobi)'
  },
  {
    id: 'pub-08',
    date: '2026-09-04',
    orderId: 'PUB-1048',
    sku: 'SOFT-TON-300',
    productName: 'Krest Tonic Water 300ml Glass',
    category: 'Soft Drinks & Mixers',
    unitsSold: 36,
    unitPrice: 130,
    revenue: 4680,
    unitCost: 60,
    profit: 2520,
    profitMarginPercent: 53.8,
    currentStock: 16,
    reorderPoint: 48,
    leadTimeDays: 2,
    supplier: 'CCBA Nairobi Bottlers'
  },
  {
    id: 'pub-09',
    date: '2026-09-05',
    orderId: 'PUB-1049',
    sku: 'BEER-TSK-500',
    productName: 'Tusker Lager 500ml Bottle',
    category: 'Beers & Ciders',
    unitsSold: 72,
    unitPrice: 300,
    revenue: 21600,
    unitCost: 210,
    profit: 6480,
    profitMarginPercent: 30.0,
    currentStock: 36,
    reorderPoint: 72,
    leadTimeDays: 2,
    supplier: 'EABL Central Depot (Ruaraka)'
  },
  {
    id: 'pub-10',
    date: '2026-09-05',
    orderId: 'PUB-1050',
    sku: 'FOOD-MBZ-1KG',
    productName: 'Mbuzi Choma (1kg Roasted Goat Meat)',
    category: 'Choma & Pub Kitchen',
    unitsSold: 14,
    unitPrice: 1400,
    revenue: 19600,
    unitCost: 850,
    profit: 7700,
    profitMarginPercent: 39.3,
    currentStock: 8,
    reorderPoint: 25,
    leadTimeDays: 1,
    supplier: 'Dagoretti Livestock & Meat Supply'
  },
  {
    id: 'pub-11',
    date: '2026-09-05',
    orderId: 'PUB-1051',
    sku: 'FOOD-CHIP-MAS',
    productName: 'Chips Masala (Spicy Pub Fries)',
    category: 'Choma & Pub Kitchen',
    unitsSold: 24,
    unitPrice: 280,
    revenue: 6720,
    unitCost: 110,
    profit: 4080,
    profitMarginPercent: 60.7,
    currentStock: 42,
    reorderPoint: 30,
    leadTimeDays: 2,
    supplier: 'Wakulima Central Market'
  },
  {
    id: 'pub-12',
    date: '2026-09-06',
    orderId: 'PUB-1052',
    sku: 'BEER-TSKC-500',
    productName: 'Tusker Premium Cider 500ml',
    category: 'Beers & Ciders',
    unitsSold: 20,
    unitPrice: 320,
    revenue: 6400,
    unitCost: 220,
    profit: 2000,
    profitMarginPercent: 31.3,
    currentStock: 18,
    reorderPoint: 36,
    leadTimeDays: 2,
    supplier: 'EABL Central Depot (Ruaraka)'
  },
  {
    id: 'pub-13',
    date: '2026-09-06',
    orderId: 'PUB-1053',
    sku: 'FOOD-KUKU-HLF',
    productName: 'Kuku Choma (Half Roast Chicken)',
    category: 'Choma & Pub Kitchen',
    unitsSold: 10,
    unitPrice: 750,
    revenue: 7500,
    unitCost: 440,
    profit: 3100,
    profitMarginPercent: 41.3,
    currentStock: 14,
    reorderPoint: 20,
    leadTimeDays: 1,
    supplier: 'Kenchic Local Distributor'
  },
  {
    id: 'pub-14',
    date: '2026-09-07',
    orderId: 'PUB-1054',
    sku: 'BEER-BLZ-500',
    productName: 'Balozi Lager 500ml (Sugar Free)',
    category: 'Beers & Ciders',
    unitsSold: 12,
    unitPrice: 280,
    revenue: 3360,
    unitCost: 195,
    profit: 1020,
    profitMarginPercent: 30.4,
    currentStock: 120,
    reorderPoint: 48,
    leadTimeDays: 2,
    supplier: 'EABL Central Depot (Ruaraka)'
  },
  {
    id: 'pub-15',
    date: '2026-09-07',
    orderId: 'PUB-1055',
    sku: 'SPRT-CHR-750',
    productName: 'Chrome Vodka 750ml',
    category: 'Spirits & Liquors',
    unitsSold: 8,
    unitPrice: 900,
    revenue: 7200,
    unitCost: 620,
    profit: 2240,
    profitMarginPercent: 31.1,
    currentStock: 26,
    reorderPoint: 20,
    leadTimeDays: 3,
    supplier: 'UDV Kenya Ltd (Nairobi)'
  },
  {
    id: 'pub-16',
    date: '2026-09-08',
    orderId: 'PUB-1056',
    sku: 'SOFT-STN-300',
    productName: 'Stoney Tangawizi 300ml Glass Bottle',
    category: 'Soft Drinks & Mixers',
    unitsSold: 30,
    unitPrice: 120,
    revenue: 3600,
    unitCost: 55,
    profit: 1950,
    profitMarginPercent: 54.2,
    currentStock: 48,
    reorderPoint: 48,
    leadTimeDays: 2,
    supplier: 'CCBA Nairobi Bottlers'
  },
  {
    id: 'pub-17',
    date: '2026-09-08',
    orderId: 'PUB-1057',
    sku: 'FOOD-UGL-SUK',
    productName: 'Ugali & Sukuma Wiki (Side Platter)',
    category: 'Choma & Pub Kitchen',
    unitsSold: 22,
    unitPrice: 120,
    revenue: 2640,
    unitCost: 35,
    profit: 1870,
    profitMarginPercent: 70.8,
    currentStock: 50,
    reorderPoint: 35,
    leadTimeDays: 1,
    supplier: 'Wakulima Central Market'
  },
  {
    id: 'pub-18',
    date: '2026-09-09',
    orderId: 'PUB-1058',
    sku: 'BEER-TSK-500',
    productName: 'Tusker Lager 500ml Bottle',
    category: 'Beers & Ciders',
    unitsSold: 60,
    unitPrice: 300,
    revenue: 18000,
    unitCost: 210,
    profit: 5400,
    profitMarginPercent: 30.0,
    currentStock: 36,
    reorderPoint: 72,
    leadTimeDays: 2,
    supplier: 'EABL Central Depot (Ruaraka)'
  },
  {
    id: 'pub-19',
    date: '2026-09-09',
    orderId: 'PUB-1059',
    sku: 'SPRT-CPT-750',
    productName: 'Captain Morgan Gold Spiced 750ml',
    category: 'Spirits & Liquors',
    unitsSold: 5,
    unitPrice: 1550,
    revenue: 7750,
    unitCost: 1080,
    profit: 2350,
    profitMarginPercent: 30.3,
    currentStock: 8,
    reorderPoint: 15,
    leadTimeDays: 3,
    supplier: 'UDV Kenya Ltd (Nairobi)'
  },
  {
    id: 'pub-20',
    date: '2026-09-10',
    orderId: 'PUB-1060',
    sku: 'FOOD-MBZ-1KG',
    productName: 'Mbuzi Choma (1kg Roasted Goat Meat)',
    category: 'Choma & Pub Kitchen',
    unitsSold: 11,
    unitPrice: 1400,
    revenue: 15400,
    unitCost: 850,
    profit: 6050,
    profitMarginPercent: 39.3,
    currentStock: 8,
    reorderPoint: 25,
    leadTimeDays: 1,
    supplier: 'Dagoretti Livestock & Meat Supply'
  },
  {
    id: 'pub-21',
    date: '2026-09-10',
    orderId: 'PUB-1061',
    sku: 'SOFT-COK-300',
    productName: 'Coca-Cola 300ml Glass Bottle',
    category: 'Soft Drinks & Mixers',
    unitsSold: 32,
    unitPrice: 120,
    revenue: 3840,
    unitCost: 55,
    profit: 2080,
    profitMarginPercent: 54.2,
    currentStock: 60,
    reorderPoint: 48,
    leadTimeDays: 2,
    supplier: 'CCBA Nairobi Bottlers'
  },
  {
    id: 'pub-22',
    date: '2026-09-11',
    orderId: 'PUB-1062',
    sku: 'BEER-GNS-500',
    productName: 'Guinness Foreign Extra Stout 500ml',
    category: 'Beers & Ciders',
    unitsSold: 30,
    unitPrice: 350,
    revenue: 10500,
    unitCost: 245,
    profit: 3150,
    profitMarginPercent: 30.0,
    currentStock: 12,
    reorderPoint: 48,
    leadTimeDays: 2,
    supplier: 'EABL Central Depot (Ruaraka)'
  },
  {
    id: 'pub-23',
    date: '2026-09-11',
    orderId: 'PUB-1063',
    sku: 'FOOD-MUTURA-PC',
    productName: 'African Spiced Sausage (Mutura)',
    category: 'Choma & Pub Kitchen',
    unitsSold: 42,
    unitPrice: 150,
    revenue: 6300,
    unitCost: 60,
    profit: 3780,
    profitMarginPercent: 60.0,
    currentStock: 18,
    reorderPoint: 40,
    leadTimeDays: 1,
    supplier: 'Dagoretti Livestock & Meat Supply'
  },
  {
    id: 'pub-24',
    date: '2026-09-12',
    orderId: 'PUB-1064',
    sku: 'SPRT-GLB-750',
    productName: 'Gilbeys Special Dry Gin 750ml',
    category: 'Spirits & Liquors',
    unitsSold: 12,
    unitPrice: 1600,
    revenue: 19200,
    unitCost: 1120,
    profit: 5760,
    profitMarginPercent: 30.0,
    currentStock: 6,
    reorderPoint: 25,
    leadTimeDays: 3,
    supplier: 'UDV Kenya Ltd (Nairobi)'
  },
  {
    id: 'pub-25',
    date: '2026-09-12',
    orderId: 'PUB-1065',
    sku: 'BEER-WTC-500',
    productName: 'White Cap Lager 500ml Bottle',
    category: 'Beers & Ciders',
    unitsSold: 36,
    unitPrice: 300,
    revenue: 10800,
    unitCost: 215,
    profit: 3060,
    profitMarginPercent: 28.3,
    currentStock: 24,
    reorderPoint: 48,
    leadTimeDays: 2,
    supplier: 'EABL Central Depot (Ruaraka)'
  },
  {
    id: 'pub-26',
    date: '2026-09-13',
    orderId: 'PUB-1066',
    sku: 'SOFT-KRG-500',
    productName: 'Keringet Natural Mineral Water 500ml',
    category: 'Soft Drinks & Mixers',
    unitsSold: 26,
    unitPrice: 100,
    revenue: 2600,
    unitCost: 40,
    profit: 1560,
    profitMarginPercent: 60.0,
    currentStock: 120,
    reorderPoint: 48,
    leadTimeDays: 2,
    supplier: 'Crown Beverages Kenya'
  },
  {
    id: 'pub-27',
    date: '2026-09-14',
    orderId: 'PUB-1067',
    sku: 'BEER-TSK-500',
    productName: 'Tusker Lager 500ml Bottle',
    category: 'Beers & Ciders',
    unitsSold: 55,
    unitPrice: 300,
    revenue: 16500,
    unitCost: 210,
    profit: 4950,
    profitMarginPercent: 30.0,
    currentStock: 36,
    reorderPoint: 72,
    leadTimeDays: 2,
    supplier: 'EABL Central Depot (Ruaraka)'
  },
  {
    id: 'pub-28',
    date: '2026-09-15',
    orderId: 'PUB-1068',
    sku: 'FOOD-MBZ-1KG',
    productName: 'Mbuzi Choma (1kg Roasted Goat Meat)',
    category: 'Choma & Pub Kitchen',
    unitsSold: 12,
    unitPrice: 1400,
    revenue: 16800,
    unitCost: 850,
    profit: 6600,
    profitMarginPercent: 39.3,
    currentStock: 8,
    reorderPoint: 25,
    leadTimeDays: 1,
    supplier: 'Dagoretti Livestock & Meat Supply'
  }
];

export function getSampleSheetRawRows(): string[][] {
  const rows: string[][] = [SAMPLE_SHEET_HEADERS];
  INITIAL_SAMPLE_SALES.forEach((rec) => {
    rows.push([
      rec.date,
      rec.orderId,
      rec.sku,
      rec.productName,
      rec.category,
      String(rec.unitsSold),
      String(rec.unitPrice),
      String(rec.revenue),
      String(rec.unitCost),
      String(rec.profit),
      String(rec.currentStock),
      String(rec.reorderPoint),
      String(rec.leadTimeDays),
      rec.supplier
    ]);
  });
  return rows;
}
